<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <AssemblyName>MenuAPI</AssemblyName>
    <TargetName>MenuAPI</TargetName>
    <DebugType>embedded</DebugType>
    <DefineConstants>FIVEM</DefineConstants>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\dependencies\shared\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <PackageReference Include="CitizenFX.Core.Client" Version="1.0.10188">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
